/pcd2pgm:
  ros__parameters:
    file_directory: src/rm_navigation/rm_perception/fast_lio/PCD/
    file_name: map_1
    flag_pass_through: false
    map_resolution: 0.05
    map_topic_name: map
    thre_radius: 0.5
    thre_z_max: 0.7
    thre_z_min: 0.3
    thres_point_count: 10
    use_sim_time: false
