/camera_node:
  ros__parameters:
    camera_info_url: package://rm_vision_bringup/config/camera_info.yaml
    exposure_time: 2000
    gain: 16.0

/serial_driver:
  ros__parameters:
    timestamp_offset: 0.006
    device_name: /dev/ttyACM0
    baud_rate: 460800
    flow_control: none
    parity: none
    stop_bits: "1"

/armor_detector:
  ros__parameters:
    debug: true

    detect_color: 1
    binary_thres: 60

    light.min_ratio: 0.1
    armor.min_light_ratio: 0.8

    classifier_threshold: 0.7
    ignore_classes: ["negative"]

/armor_tracker:
  ros__parameters:
    target_frame: gimbal_odom
    max_armor_distance: 10.0
  
    ekf:
      sigma2_q_xyz: 0.05
      sigma2_q_yaw: 5.0
      sigma2_q_r: 80.0

      r_xyz_factor: 4e-5
      r_yaw: 5e-3

    tracker:
      max_match_distance: 0.5
      max_match_yaw_diff: 1.0

      k: 0.038
      bias_time: 100
      s_bias: 0.11
      z_bias: 0.0


      tracking_thres: 0
      lost_time_thres: 3.0
